import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ar" | "tr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.courses": "Courses",
    "nav.learn": "Interactive Learning",
    "nav.blog": "Blog",
    "nav.support": "Support",
    "nav.login": "Login",
    "nav.signup": "Sign Up",
    "nav.dashboard": "Dashboard",
    // Hero
    "hero.title": "From Ahlan to Fluency",
    "hero.subtitle": "Master Arabic with interactive courses, quizzes, and personalized learning paths designed for every level.",
    "hero.cta": "Start Learning",
    "hero.placement": "Take Placement Test",
    // Courses
    "courses.title": "Our Courses",
    "courses.subtitle": "Choose your level and start your Arabic journey",
    "courses.beginner": "Beginner",
    "courses.intermediate": "Intermediate",
    "courses.advanced": "Advanced",
    "courses.beginner.desc": "Learn the Arabic alphabet, basic greetings, and fundamental grammar.",
    "courses.intermediate.desc": "Build sentences, expand vocabulary, and master conversational Arabic.",
    "courses.advanced.desc": "Perfect your fluency with literature, dialects, and professional Arabic.",
    "courses.lessons": "lessons",
    "courses.start": "Start Course",
    "courses.locked": "Complete previous level first",
    // Featured
    "featured.title": "Featured Courses",
    "featured.subtitle": "Hand-picked courses to accelerate your learning",
    // Quiz
    "quiz.title": "Interactive Learning",
    "quiz.subtitle": "Test your knowledge with quizzes and exercises",
    "quiz.start": "Start Quiz",
    "quiz.next": "Next",
    "quiz.check": "Check Answer",
    "quiz.correct": "Correct!",
    "quiz.incorrect": "Try again!",
    "quiz.score": "Your Score",
    "quiz.restart": "Try Again",
    "quiz.complete": "Quiz Complete!",
    "quiz.multiplechoice": "Multiple Choice",
    "quiz.writing": "Writing Exercise",
    "quiz.game": "Word Game",
    // Login
    "login.title": "Welcome Back",
    "login.subtitle": "Sign in to continue your learning journey",
    "login.email": "Email",
    "login.password": "Password",
    "login.signin": "Sign In",
    "login.signup": "Sign Up",
    "login.or": "or continue with",
    "login.google": "Google",
    "login.facebook": "Facebook",
    "login.noaccount": "Don't have an account?",
    "login.hasaccount": "Already have an account?",
    "login.name": "Full Name",
    "login.create": "Create Account",
    // Blog
    "blog.title": "Blog",
    "blog.subtitle": "Tips, stories, and insights for Arabic learners",
    "blog.readmore": "Read More",
    // Support
    "support.title": "Support",
    "support.subtitle": "We're here to help you on your learning journey",
    "support.name": "Your Name",
    "support.email": "Email",
    "support.message": "Message",
    "support.send": "Send Message",
    "support.sent": "Message sent! We'll get back to you soon.",
    // Dashboard
    "dashboard.title": "Your Dashboard",
    "dashboard.progress": "Overall Progress",
    "dashboard.courses": "My Courses",
    "dashboard.achievements": "Achievements",
    "dashboard.ongoing": "Ongoing",
    "dashboard.completed": "Completed",
    "dashboard.streak": "Day Streak",
    "dashboard.points": "Points",
    // Footer
    "footer.tagline": "From Ahlan to Fluency — Your journey to mastering Arabic starts here.",
    "footer.rights": "All rights reserved.",
    "nav.teachers": "Teachers",
    "teachers.title": "Meet Our Teachers",
    "teachers.subtitle": "Our volunteer teachers are here to help you learn Arabic for free. They offer guidance, conversation practice, and answers to your questions — all at no cost.",
    "teachers.cta": "Browse the profiles below and reach out to a teacher today!",
    "teachers.yearsExp": "years of experience",
    "teachers.email": "Email",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.courses": "الدورات",
    "nav.learn": "التعلم التفاعلي",
    "nav.blog": "المدونة",
    "nav.support": "الدعم",
    "nav.login": "تسجيل الدخول",
    "nav.signup": "إنشاء حساب",
    "nav.dashboard": "لوحة التحكم",
    "hero.title": "من أهلاً إلى الطلاقة",
    "hero.subtitle": "أتقن العربية مع دورات تفاعلية واختبارات ومسارات تعلم مخصصة لكل مستوى.",
    "hero.cta": "ابدأ التعلم",
    "hero.placement": "خذ اختبار تحديد المستوى",
    "courses.title": "دوراتنا",
    "courses.subtitle": "اختر مستواك وابدأ رحلتك في تعلم العربية",
    "courses.beginner": "مبتدئ",
    "courses.intermediate": "متوسط",
    "courses.advanced": "متقدم",
    "courses.beginner.desc": "تعلم الأبجدية العربية والتحيات الأساسية والقواعد الأولية.",
    "courses.intermediate.desc": "بناء الجمل وتوسيع المفردات وإتقان المحادثة العربية.",
    "courses.advanced.desc": "أتقن طلاقتك مع الأدب واللهجات والعربية المهنية.",
    "courses.lessons": "دروس",
    "courses.start": "ابدأ الدورة",
    "courses.locked": "أكمل المستوى السابق أولاً",
    "featured.title": "الدورات المميزة",
    "featured.subtitle": "دورات مختارة بعناية لتسريع تعلمك",
    "quiz.title": "التعلم التفاعلي",
    "quiz.subtitle": "اختبر معرفتك بالاختبارات والتمارين",
    "quiz.start": "ابدأ الاختبار",
    "quiz.next": "التالي",
    "quiz.check": "تحقق من الإجابة",
    "quiz.correct": "!صحيح",
    "quiz.incorrect": "!حاول مرة أخرى",
    "quiz.score": "نتيجتك",
    "quiz.restart": "حاول مرة أخرى",
    "quiz.complete": "!اكتمل الاختبار",
    "quiz.multiplechoice": "اختيار من متعدد",
    "quiz.writing": "تمرين كتابة",
    "quiz.game": "لعبة الكلمات",
    "login.title": "مرحبًا بعودتك",
    "login.subtitle": "سجل دخولك لمتابعة رحلة التعلم",
    "login.email": "البريد الإلكتروني",
    "login.password": "كلمة المرور",
    "login.signin": "تسجيل الدخول",
    "login.signup": "إنشاء حساب",
    "login.or": "أو تابع مع",
    "login.google": "جوجل",
    "login.facebook": "فيسبوك",
    "login.noaccount": "ليس لديك حساب؟",
    "login.hasaccount": "لديك حساب بالفعل؟",
    "login.name": "الاسم الكامل",
    "login.create": "إنشاء حساب",
    "blog.title": "المدونة",
    "blog.subtitle": "نصائح وقصص ورؤى لمتعلمي العربية",
    "blog.readmore": "اقرأ المزيد",
    "support.title": "الدعم",
    "support.subtitle": "نحن هنا لمساعدتك في رحلة التعلم",
    "support.name": "اسمك",
    "support.email": "البريد الإلكتروني",
    "support.message": "الرسالة",
    "support.send": "إرسال الرسالة",
    "support.sent": "تم إرسال الرسالة! سنرد عليك قريبًا.",
    "dashboard.title": "لوحة التحكم",
    "dashboard.progress": "التقدم العام",
    "dashboard.courses": "دوراتي",
    "dashboard.achievements": "الإنجازات",
    "dashboard.ongoing": "جارية",
    "dashboard.completed": "مكتملة",
    "dashboard.streak": "أيام متتالية",
    "dashboard.points": "نقاط",
    "footer.tagline": "من أهلاً إلى الطلاقة — رحلتك لإتقان العربية تبدأ هنا.",
    "footer.rights": "جميع الحقوق محفوظة.",
    "nav.teachers": "المعلمون",
    "teachers.title": "تعرّف على معلمينا",
    "teachers.subtitle": "معلمونا المتطوعون هنا لمساعدتك في تعلم العربية مجانًا. يقدمون التوجيه وممارسة المحادثة والإجابة على أسئلتك — بدون أي تكلفة.",
    "teachers.cta": "تصفح الملفات أدناه وتواصل مع معلم اليوم!",
    "teachers.yearsExp": "سنوات خبرة",
    "teachers.email": "بريد إلكتروني",
  },
  tr: {
    "nav.home": "Ana Sayfa",
    "nav.courses": "Kurslar",
    "nav.learn": "İnteraktif Öğrenme",
    "nav.blog": "Blog",
    "nav.support": "Destek",
    "nav.login": "Giriş Yap",
    "nav.signup": "Kayıt Ol",
    "nav.dashboard": "Kontrol Paneli",
    "hero.title": "Merhaba'dan Akıcılığa",
    "hero.subtitle": "Her seviye için tasarlanmış interaktif kurslar, quizler ve kişiselleştirilmiş öğrenme yollarıyla Arapçayı öğrenin.",
    "hero.cta": "Öğrenmeye Başla",
    "hero.placement": "Seviye Testi Yapın",
    "courses.title": "Kurslarımız",
    "courses.subtitle": "Seviyenizi seçin ve Arapça yolculuğunuza başlayın",
    "courses.beginner": "Başlangıç",
    "courses.intermediate": "Orta",
    "courses.advanced": "İleri",
    "courses.beginner.desc": "Arap alfabesini, temel selamlamaları ve temel grameri öğrenin.",
    "courses.intermediate.desc": "Cümleler kurun, kelime dağarcığını genişletin ve konuşma Arapçasını öğrenin.",
    "courses.advanced.desc": "Edebiyat, lehçeler ve profesyonel Arapça ile akıcılığınızı mükemmelleştirin.",
    "courses.lessons": "ders",
    "courses.start": "Kursa Başla",
    "courses.locked": "Önce önceki seviyeyi tamamlayın",
    "featured.title": "Öne Çıkan Kurslar",
    "featured.subtitle": "Öğrenmenizi hızlandırmak için seçilmiş kurslar",
    "quiz.title": "İnteraktif Öğrenme",
    "quiz.subtitle": "Quizler ve alıştırmalarla bilginizi test edin",
    "quiz.start": "Quize Başla",
    "quiz.next": "Sonraki",
    "quiz.check": "Cevabı Kontrol Et",
    "quiz.correct": "Doğru!",
    "quiz.incorrect": "Tekrar deneyin!",
    "quiz.score": "Puanınız",
    "quiz.restart": "Tekrar Dene",
    "quiz.complete": "Quiz Tamamlandı!",
    "quiz.multiplechoice": "Çoktan Seçmeli",
    "quiz.writing": "Yazma Alıştırması",
    "quiz.game": "Kelime Oyunu",
    "login.title": "Tekrar Hoş Geldiniz",
    "login.subtitle": "Öğrenme yolculuğunuza devam etmek için giriş yapın",
    "login.email": "E-posta",
    "login.password": "Şifre",
    "login.signin": "Giriş Yap",
    "login.signup": "Kayıt Ol",
    "login.or": "veya şununla devam edin",
    "login.google": "Google",
    "login.facebook": "Facebook",
    "login.noaccount": "Hesabınız yok mu?",
    "login.hasaccount": "Zaten hesabınız var mı?",
    "login.name": "Ad Soyad",
    "login.create": "Hesap Oluştur",
    "blog.title": "Blog",
    "blog.subtitle": "Arapça öğrenenler için ipuçları, hikayeler ve görüşler",
    "blog.readmore": "Devamını Oku",
    "support.title": "Destek",
    "support.subtitle": "Öğrenme yolculuğunuzda size yardımcı olmak için buradayız",
    "support.name": "Adınız",
    "support.email": "E-posta",
    "support.message": "Mesaj",
    "support.send": "Mesaj Gönder",
    "support.sent": "Mesaj gönderildi! En kısa sürede size döneceğiz.",
    "dashboard.title": "Kontrol Paneliniz",
    "dashboard.progress": "Genel İlerleme",
    "dashboard.courses": "Kurslarım",
    "dashboard.achievements": "Başarılar",
    "dashboard.ongoing": "Devam Eden",
    "dashboard.completed": "Tamamlanan",
    "dashboard.streak": "Gün Serisi",
    "dashboard.points": "Puan",
    "footer.tagline": "Merhaba'dan Akıcılığa — Arapça öğrenme yolculuğunuz burada başlıyor.",
    "footer.rights": "Tüm hakları saklıdır.",
    "nav.teachers": "Öğretmenler",
    "teachers.title": "Öğretmenlerimizle Tanışın",
    "teachers.subtitle": "Gönüllü öğretmenlerimiz size ücretsiz Arapça öğrenmenizde yardımcı olmak için burada. Rehberlik, konuşma pratiği ve sorularınıza cevaplar sunuyorlar — tamamen ücretsiz.",
    "teachers.cta": "Aşağıdaki profilleri inceleyin ve bugün bir öğretmenle iletişime geçin!",
    "teachers.yearsExp": "yıl deneyim",
    "teachers.email": "E-posta",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      <div dir={dir}>{children}</div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
